Vagrant.configure("2") do |config|
  $script = <<-SCRIPT
    sudo apt-get update
    sudo apt-get install nodejs -y
    sudo apt-get install npm -y
    cd /app
    rm -f package-lock.json
    npm cache clean --force
    npm install --force
    npm install react-scripts
    npm start
  SCRIPT

  config.vm.synced_folder "./", "/app"
  config.vm.box = "ubuntu/xenial64"
  config.ssh.forward_x11 = true
  config.vm.provider :libvirt do |domain|
    domain.cpus = 4
    domain.memory = 30000
  end
  config.vm.provision "shell", inline: $script, privileged: true
end
