# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 5000, host: 8080
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip git
    git clone https://github.com/do-community/flask_blog.git /home/vagrant/flask_blog
    cd flask_blog && export FLASK_APP="app.py"
    pip3 freeze > requirements.txt
    pip3 install -r requirements.txt
    sudo apt install python3-flask -y
    export FLASK_APP=app.py
    nohup python3 app.py
  SHELL
end